### ISSUE TITLE
Can I run this on Asus 66u_b1 with merlin?

### ISSUE THREAD

**Issue by ShadowEmbrace** [miniers/openwrt-mosdns#1]
I'm thinking about setting up a mosdns on my router.

**Comment by miniers** [comment]
不清楚，这个只是给openwrt编译用的😂，没编译过梅林

**Comment by ShadowEmbrace** [comment]
> 
> 
> 不清楚，这个只是给openwrt编译用的😂，没编译过梅林

谢谢
